import type {Frequency, Tier} from "./pricing-types";

import {FrequencyEnum, TiersEnum} from "./pricing-types";

export const frequencies: Array<Frequency> = [
  {key: FrequencyEnum.Monthly, label: "Pay Monthly", priceSuffix: "per month"},
  {key: FrequencyEnum.Yearly, label: "Pay Yearly", priceSuffix: "per year"},
];

export const tiers: Array<Tier> = [
  {
    key: TiersEnum.Free,
    title: "Free",
    price: "Free",
    href: "/signup",
    featured: false,
    mostPopular: false,
    description: "For casual players exploring competitive gaming and community features.",
    targetAudience: "Casual Players",
    features: [
      "5 replay uploads/month",
      "500 MB cloud storage",
      "Basic analytics (K/D, ADR, Rating)",
      "Casual matchmaking queue",
      "1 squad with up to 5 players",
      "Community forums & chat",
      "Community tournament access",
      "Achievement tracking",
    ],
    buttonText: "Start for Free",
    buttonColor: "default",
    buttonVariant: "flat",
  },
  {
    key: TiersEnum.Pro,
    title: "Pro",
    description: "For competitive players serious about improving their game with advanced tools.",
    targetAudience: "Competitive Players",
    href: "/checkout?plan=pro",
    mostPopular: true,
    badge: "Most Popular",
    price: {
      monthly: "$9.99",
      yearly: "$7.99",
    },
    featured: false,
    features: [
      "Unlimited replay uploads",
      "25 GB cloud storage",
      "Advanced analytics & AI insights",
      "Priority matchmaking queue",
      "Ranked & competitive queues",
      "3 squads with up to 10 players each",
      "Skill-based wager matches",
      "Ad-free experience",
      "Discord integration",
      "Priority email support",
      "Early access to new features",
      "Exclusive pro content & guides",
    ],
    buttonText: "Get Pro",
    buttonColor: "primary",
    buttonVariant: "solid",
  },
  {
    key: TiersEnum.Team,
    title: "Team",
    href: "/checkout?plan=team",
    featured: true,
    mostPopular: false,
    badge: "Best for Teams",
    description: "Complete team management with analytics, scrim scheduling, and shared resources.",
    targetAudience: "Esports Teams",
    price: {
      monthly: "$29.99",
      yearly: "$23.99",
    },
    priceSuffix: "for 10 seats",
    features: [
      "Everything in Pro, plus:",
      "100 GB shared team storage",
      "Team analytics dashboard",
      "Opponent research & scouting",
      "Scrim scheduling calendar",
      "10 squads with 25 players each",
      "Host up to 3 tournaments/month",
      "Custom team branding",
      "API access & webhooks",
      "Full Discord bot integration",
      "Team wallet & prize payouts",
      "Phone & email support",
    ],
    buttonText: "Get Team",
    buttonColor: "secondary",
    buttonVariant: "solid",
  },
  {
    key: TiersEnum.Organizer,
    title: "Organizer",
    href: "/contact?plan=organizer",
    featured: false,
    mostPopular: false,
    badge: "Enterprise",
    description: "Professional tournament hosting with white-label branding and automated prize distribution.",
    targetAudience: "Tournament Organizers",
    price: {
      monthly: "$99.99",
      yearly: "$79.99",
    },
    features: [
      "Everything in Team, plus:",
      "500 GB enterprise storage",
      "Unlimited tournament hosting",
      "Automated prize distribution",
      "White-label platform branding",
      "Custom sponsor integrations",
      "Stream & broadcast tools",
      "Unlimited staff seats",
      "Custom matchmaking pools",
      "Enterprise analytics & reporting",
      "Custom Discord bot",
      "Dedicated account manager",
      "Custom email templates",
      "SLA guarantee",
    ],
    buttonText: "Contact Sales",
    buttonColor: "default",
    buttonVariant: "bordered",
  },
];

// Plan IDs for backend integration (stable UUIDs)
export const PLAN_IDS = {
  [TiersEnum.Free]: "00000000-0000-0000-0001-000000000001",
  [TiersEnum.Pro]: "00000000-0000-0000-0001-000000000002",
  [TiersEnum.Team]: "00000000-0000-0000-0001-000000000003",
  [TiersEnum.Organizer]: "00000000-0000-0000-0001-000000000004",
} as const;
